// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageModels.proto

package com.spiky.server.protomodels;

public final class MessageModels {
  private MessageModels() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CryptogramWrapperOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CryptogramWrapper)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bytes registration = 1;</code>
     */
    com.google.protobuf.ByteString getRegistration();

    /**
     * <code>optional bytes login = 2;</code>
     */
    com.google.protobuf.ByteString getLogin();

    /**
     * <code>optional bytes initialState = 3;</code>
     */
    com.google.protobuf.ByteString getInitialState();

    /**
     * <code>optional bytes room = 4;</code>
     */
    com.google.protobuf.ByteString getRoom();

    /**
     * <code>optional bytes mainMenu = 5;</code>
     */
    com.google.protobuf.ByteString getMainMenu();

    /**
     * <code>optional bytes gameModels = 6;</code>
     */
    com.google.protobuf.ByteString getGameModels();
  }
  /**
   * Protobuf type {@code CryptogramWrapper}
   */
  public  static final class CryptogramWrapper extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:CryptogramWrapper)
      CryptogramWrapperOrBuilder {
    // Use CryptogramWrapper.newBuilder() to construct.
    private CryptogramWrapper(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private CryptogramWrapper() {
      registration_ = com.google.protobuf.ByteString.EMPTY;
      login_ = com.google.protobuf.ByteString.EMPTY;
      initialState_ = com.google.protobuf.ByteString.EMPTY;
      room_ = com.google.protobuf.ByteString.EMPTY;
      mainMenu_ = com.google.protobuf.ByteString.EMPTY;
      gameModels_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private CryptogramWrapper(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {

              registration_ = input.readBytes();
              break;
            }
            case 18: {

              login_ = input.readBytes();
              break;
            }
            case 26: {

              initialState_ = input.readBytes();
              break;
            }
            case 34: {

              room_ = input.readBytes();
              break;
            }
            case 42: {

              mainMenu_ = input.readBytes();
              break;
            }
            case 50: {

              gameModels_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.spiky.server.protomodels.MessageModels.internal_static_CryptogramWrapper_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.spiky.server.protomodels.MessageModels.internal_static_CryptogramWrapper_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.spiky.server.protomodels.MessageModels.CryptogramWrapper.class, com.spiky.server.protomodels.MessageModels.CryptogramWrapper.Builder.class);
    }

    public static final int REGISTRATION_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString registration_;
    /**
     * <code>optional bytes registration = 1;</code>
     */
    public com.google.protobuf.ByteString getRegistration() {
      return registration_;
    }

    public static final int LOGIN_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString login_;
    /**
     * <code>optional bytes login = 2;</code>
     */
    public com.google.protobuf.ByteString getLogin() {
      return login_;
    }

    public static final int INITIALSTATE_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString initialState_;
    /**
     * <code>optional bytes initialState = 3;</code>
     */
    public com.google.protobuf.ByteString getInitialState() {
      return initialState_;
    }

    public static final int ROOM_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString room_;
    /**
     * <code>optional bytes room = 4;</code>
     */
    public com.google.protobuf.ByteString getRoom() {
      return room_;
    }

    public static final int MAINMENU_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString mainMenu_;
    /**
     * <code>optional bytes mainMenu = 5;</code>
     */
    public com.google.protobuf.ByteString getMainMenu() {
      return mainMenu_;
    }

    public static final int GAMEMODELS_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString gameModels_;
    /**
     * <code>optional bytes gameModels = 6;</code>
     */
    public com.google.protobuf.ByteString getGameModels() {
      return gameModels_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!registration_.isEmpty()) {
        output.writeBytes(1, registration_);
      }
      if (!login_.isEmpty()) {
        output.writeBytes(2, login_);
      }
      if (!initialState_.isEmpty()) {
        output.writeBytes(3, initialState_);
      }
      if (!room_.isEmpty()) {
        output.writeBytes(4, room_);
      }
      if (!mainMenu_.isEmpty()) {
        output.writeBytes(5, mainMenu_);
      }
      if (!gameModels_.isEmpty()) {
        output.writeBytes(6, gameModels_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!registration_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, registration_);
      }
      if (!login_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, login_);
      }
      if (!initialState_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, initialState_);
      }
      if (!room_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, room_);
      }
      if (!mainMenu_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, mainMenu_);
      }
      if (!gameModels_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, gameModels_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.spiky.server.protomodels.MessageModels.CryptogramWrapper)) {
        return super.equals(obj);
      }
      com.spiky.server.protomodels.MessageModels.CryptogramWrapper other = (com.spiky.server.protomodels.MessageModels.CryptogramWrapper) obj;

      boolean result = true;
      result = result && getRegistration()
          .equals(other.getRegistration());
      result = result && getLogin()
          .equals(other.getLogin());
      result = result && getInitialState()
          .equals(other.getInitialState());
      result = result && getRoom()
          .equals(other.getRoom());
      result = result && getMainMenu()
          .equals(other.getMainMenu());
      result = result && getGameModels()
          .equals(other.getGameModels());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + REGISTRATION_FIELD_NUMBER;
      hash = (53 * hash) + getRegistration().hashCode();
      hash = (37 * hash) + LOGIN_FIELD_NUMBER;
      hash = (53 * hash) + getLogin().hashCode();
      hash = (37 * hash) + INITIALSTATE_FIELD_NUMBER;
      hash = (53 * hash) + getInitialState().hashCode();
      hash = (37 * hash) + ROOM_FIELD_NUMBER;
      hash = (53 * hash) + getRoom().hashCode();
      hash = (37 * hash) + MAINMENU_FIELD_NUMBER;
      hash = (53 * hash) + getMainMenu().hashCode();
      hash = (37 * hash) + GAMEMODELS_FIELD_NUMBER;
      hash = (53 * hash) + getGameModels().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.spiky.server.protomodels.MessageModels.CryptogramWrapper parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.spiky.server.protomodels.MessageModels.CryptogramWrapper parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.spiky.server.protomodels.MessageModels.CryptogramWrapper parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.spiky.server.protomodels.MessageModels.CryptogramWrapper parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.spiky.server.protomodels.MessageModels.CryptogramWrapper parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.spiky.server.protomodels.MessageModels.CryptogramWrapper parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.spiky.server.protomodels.MessageModels.CryptogramWrapper parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.spiky.server.protomodels.MessageModels.CryptogramWrapper parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.spiky.server.protomodels.MessageModels.CryptogramWrapper parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.spiky.server.protomodels.MessageModels.CryptogramWrapper parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.spiky.server.protomodels.MessageModels.CryptogramWrapper prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CryptogramWrapper}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CryptogramWrapper)
        com.spiky.server.protomodels.MessageModels.CryptogramWrapperOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.spiky.server.protomodels.MessageModels.internal_static_CryptogramWrapper_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.spiky.server.protomodels.MessageModels.internal_static_CryptogramWrapper_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.spiky.server.protomodels.MessageModels.CryptogramWrapper.class, com.spiky.server.protomodels.MessageModels.CryptogramWrapper.Builder.class);
      }

      // Construct using com.spiky.server.protomodels.MessageModels.CryptogramWrapper.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        registration_ = com.google.protobuf.ByteString.EMPTY;

        login_ = com.google.protobuf.ByteString.EMPTY;

        initialState_ = com.google.protobuf.ByteString.EMPTY;

        room_ = com.google.protobuf.ByteString.EMPTY;

        mainMenu_ = com.google.protobuf.ByteString.EMPTY;

        gameModels_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.spiky.server.protomodels.MessageModels.internal_static_CryptogramWrapper_descriptor;
      }

      public com.spiky.server.protomodels.MessageModels.CryptogramWrapper getDefaultInstanceForType() {
        return com.spiky.server.protomodels.MessageModels.CryptogramWrapper.getDefaultInstance();
      }

      public com.spiky.server.protomodels.MessageModels.CryptogramWrapper build() {
        com.spiky.server.protomodels.MessageModels.CryptogramWrapper result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.spiky.server.protomodels.MessageModels.CryptogramWrapper buildPartial() {
        com.spiky.server.protomodels.MessageModels.CryptogramWrapper result = new com.spiky.server.protomodels.MessageModels.CryptogramWrapper(this);
        result.registration_ = registration_;
        result.login_ = login_;
        result.initialState_ = initialState_;
        result.room_ = room_;
        result.mainMenu_ = mainMenu_;
        result.gameModels_ = gameModels_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.spiky.server.protomodels.MessageModels.CryptogramWrapper) {
          return mergeFrom((com.spiky.server.protomodels.MessageModels.CryptogramWrapper)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.spiky.server.protomodels.MessageModels.CryptogramWrapper other) {
        if (other == com.spiky.server.protomodels.MessageModels.CryptogramWrapper.getDefaultInstance()) return this;
        if (other.getRegistration() != com.google.protobuf.ByteString.EMPTY) {
          setRegistration(other.getRegistration());
        }
        if (other.getLogin() != com.google.protobuf.ByteString.EMPTY) {
          setLogin(other.getLogin());
        }
        if (other.getInitialState() != com.google.protobuf.ByteString.EMPTY) {
          setInitialState(other.getInitialState());
        }
        if (other.getRoom() != com.google.protobuf.ByteString.EMPTY) {
          setRoom(other.getRoom());
        }
        if (other.getMainMenu() != com.google.protobuf.ByteString.EMPTY) {
          setMainMenu(other.getMainMenu());
        }
        if (other.getGameModels() != com.google.protobuf.ByteString.EMPTY) {
          setGameModels(other.getGameModels());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.spiky.server.protomodels.MessageModels.CryptogramWrapper parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.spiky.server.protomodels.MessageModels.CryptogramWrapper) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString registration_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes registration = 1;</code>
       */
      public com.google.protobuf.ByteString getRegistration() {
        return registration_;
      }
      /**
       * <code>optional bytes registration = 1;</code>
       */
      public Builder setRegistration(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        registration_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes registration = 1;</code>
       */
      public Builder clearRegistration() {
        
        registration_ = getDefaultInstance().getRegistration();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString login_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes login = 2;</code>
       */
      public com.google.protobuf.ByteString getLogin() {
        return login_;
      }
      /**
       * <code>optional bytes login = 2;</code>
       */
      public Builder setLogin(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        login_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes login = 2;</code>
       */
      public Builder clearLogin() {
        
        login_ = getDefaultInstance().getLogin();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString initialState_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes initialState = 3;</code>
       */
      public com.google.protobuf.ByteString getInitialState() {
        return initialState_;
      }
      /**
       * <code>optional bytes initialState = 3;</code>
       */
      public Builder setInitialState(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        initialState_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes initialState = 3;</code>
       */
      public Builder clearInitialState() {
        
        initialState_ = getDefaultInstance().getInitialState();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString room_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes room = 4;</code>
       */
      public com.google.protobuf.ByteString getRoom() {
        return room_;
      }
      /**
       * <code>optional bytes room = 4;</code>
       */
      public Builder setRoom(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        room_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes room = 4;</code>
       */
      public Builder clearRoom() {
        
        room_ = getDefaultInstance().getRoom();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString mainMenu_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes mainMenu = 5;</code>
       */
      public com.google.protobuf.ByteString getMainMenu() {
        return mainMenu_;
      }
      /**
       * <code>optional bytes mainMenu = 5;</code>
       */
      public Builder setMainMenu(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        mainMenu_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes mainMenu = 5;</code>
       */
      public Builder clearMainMenu() {
        
        mainMenu_ = getDefaultInstance().getMainMenu();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString gameModels_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes gameModels = 6;</code>
       */
      public com.google.protobuf.ByteString getGameModels() {
        return gameModels_;
      }
      /**
       * <code>optional bytes gameModels = 6;</code>
       */
      public Builder setGameModels(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        gameModels_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes gameModels = 6;</code>
       */
      public Builder clearGameModels() {
        
        gameModels_ = getDefaultInstance().getGameModels();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:CryptogramWrapper)
    }

    // @@protoc_insertion_point(class_scope:CryptogramWrapper)
    private static final com.spiky.server.protomodels.MessageModels.CryptogramWrapper DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.spiky.server.protomodels.MessageModels.CryptogramWrapper();
    }

    public static com.spiky.server.protomodels.MessageModels.CryptogramWrapper getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CryptogramWrapper>
        PARSER = new com.google.protobuf.AbstractParser<CryptogramWrapper>() {
      public CryptogramWrapper parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CryptogramWrapper(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CryptogramWrapper> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CryptogramWrapper> getParserForType() {
      return PARSER;
    }

    public com.spiky.server.protomodels.MessageModels.CryptogramWrapper getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface WrapperOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Wrapper)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .Utility utility = 1;</code>
     */
    boolean hasUtility();
    /**
     * <code>optional .Utility utility = 1;</code>
     */
    com.spiky.server.protomodels.UtilityModels.Utility getUtility();
    /**
     * <code>optional .Utility utility = 1;</code>
     */
    com.spiky.server.protomodels.UtilityModels.UtilityOrBuilder getUtilityOrBuilder();

    /**
     * <code>optional .InputChecking inputChecking = 2;</code>
     */
    boolean hasInputChecking();
    /**
     * <code>optional .InputChecking inputChecking = 2;</code>
     */
    com.spiky.server.protomodels.RegistrationLoginModels.InputChecking getInputChecking();
    /**
     * <code>optional .InputChecking inputChecking = 2;</code>
     */
    com.spiky.server.protomodels.RegistrationLoginModels.InputCheckingOrBuilder getInputCheckingOrBuilder();

    /**
     * <code>optional .Registration registration = 3;</code>
     */
    boolean hasRegistration();
    /**
     * <code>optional .Registration registration = 3;</code>
     */
    com.spiky.server.protomodels.RegistrationLoginModels.Registration getRegistration();
    /**
     * <code>optional .Registration registration = 3;</code>
     */
    com.spiky.server.protomodels.RegistrationLoginModels.RegistrationOrBuilder getRegistrationOrBuilder();

    /**
     * <code>optional .Login login = 4;</code>
     */
    boolean hasLogin();
    /**
     * <code>optional .Login login = 4;</code>
     */
    com.spiky.server.protomodels.RegistrationLoginModels.Login getLogin();
    /**
     * <code>optional .Login login = 4;</code>
     */
    com.spiky.server.protomodels.RegistrationLoginModels.LoginOrBuilder getLoginOrBuilder();

    /**
     * <code>optional .CryptogramWrapper cryptogramWrapper = 5;</code>
     */
    boolean hasCryptogramWrapper();
    /**
     * <code>optional .CryptogramWrapper cryptogramWrapper = 5;</code>
     */
    com.spiky.server.protomodels.MessageModels.CryptogramWrapper getCryptogramWrapper();
    /**
     * <code>optional .CryptogramWrapper cryptogramWrapper = 5;</code>
     */
    com.spiky.server.protomodels.MessageModels.CryptogramWrapperOrBuilder getCryptogramWrapperOrBuilder();
  }
  /**
   * Protobuf type {@code Wrapper}
   */
  public  static final class Wrapper extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Wrapper)
      WrapperOrBuilder {
    // Use Wrapper.newBuilder() to construct.
    private Wrapper(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Wrapper() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Wrapper(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.spiky.server.protomodels.UtilityModels.Utility.Builder subBuilder = null;
              if (utility_ != null) {
                subBuilder = utility_.toBuilder();
              }
              utility_ = input.readMessage(com.spiky.server.protomodels.UtilityModels.Utility.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(utility_);
                utility_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              com.spiky.server.protomodels.RegistrationLoginModels.InputChecking.Builder subBuilder = null;
              if (inputChecking_ != null) {
                subBuilder = inputChecking_.toBuilder();
              }
              inputChecking_ = input.readMessage(com.spiky.server.protomodels.RegistrationLoginModels.InputChecking.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(inputChecking_);
                inputChecking_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              com.spiky.server.protomodels.RegistrationLoginModels.Registration.Builder subBuilder = null;
              if (registration_ != null) {
                subBuilder = registration_.toBuilder();
              }
              registration_ = input.readMessage(com.spiky.server.protomodels.RegistrationLoginModels.Registration.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(registration_);
                registration_ = subBuilder.buildPartial();
              }

              break;
            }
            case 34: {
              com.spiky.server.protomodels.RegistrationLoginModels.Login.Builder subBuilder = null;
              if (login_ != null) {
                subBuilder = login_.toBuilder();
              }
              login_ = input.readMessage(com.spiky.server.protomodels.RegistrationLoginModels.Login.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(login_);
                login_ = subBuilder.buildPartial();
              }

              break;
            }
            case 42: {
              com.spiky.server.protomodels.MessageModels.CryptogramWrapper.Builder subBuilder = null;
              if (cryptogramWrapper_ != null) {
                subBuilder = cryptogramWrapper_.toBuilder();
              }
              cryptogramWrapper_ = input.readMessage(com.spiky.server.protomodels.MessageModels.CryptogramWrapper.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(cryptogramWrapper_);
                cryptogramWrapper_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.spiky.server.protomodels.MessageModels.internal_static_Wrapper_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.spiky.server.protomodels.MessageModels.internal_static_Wrapper_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.spiky.server.protomodels.MessageModels.Wrapper.class, com.spiky.server.protomodels.MessageModels.Wrapper.Builder.class);
    }

    public static final int UTILITY_FIELD_NUMBER = 1;
    private com.spiky.server.protomodels.UtilityModels.Utility utility_;
    /**
     * <code>optional .Utility utility = 1;</code>
     */
    public boolean hasUtility() {
      return utility_ != null;
    }
    /**
     * <code>optional .Utility utility = 1;</code>
     */
    public com.spiky.server.protomodels.UtilityModels.Utility getUtility() {
      return utility_ == null ? com.spiky.server.protomodels.UtilityModels.Utility.getDefaultInstance() : utility_;
    }
    /**
     * <code>optional .Utility utility = 1;</code>
     */
    public com.spiky.server.protomodels.UtilityModels.UtilityOrBuilder getUtilityOrBuilder() {
      return getUtility();
    }

    public static final int INPUTCHECKING_FIELD_NUMBER = 2;
    private com.spiky.server.protomodels.RegistrationLoginModels.InputChecking inputChecking_;
    /**
     * <code>optional .InputChecking inputChecking = 2;</code>
     */
    public boolean hasInputChecking() {
      return inputChecking_ != null;
    }
    /**
     * <code>optional .InputChecking inputChecking = 2;</code>
     */
    public com.spiky.server.protomodels.RegistrationLoginModels.InputChecking getInputChecking() {
      return inputChecking_ == null ? com.spiky.server.protomodels.RegistrationLoginModels.InputChecking.getDefaultInstance() : inputChecking_;
    }
    /**
     * <code>optional .InputChecking inputChecking = 2;</code>
     */
    public com.spiky.server.protomodels.RegistrationLoginModels.InputCheckingOrBuilder getInputCheckingOrBuilder() {
      return getInputChecking();
    }

    public static final int REGISTRATION_FIELD_NUMBER = 3;
    private com.spiky.server.protomodels.RegistrationLoginModels.Registration registration_;
    /**
     * <code>optional .Registration registration = 3;</code>
     */
    public boolean hasRegistration() {
      return registration_ != null;
    }
    /**
     * <code>optional .Registration registration = 3;</code>
     */
    public com.spiky.server.protomodels.RegistrationLoginModels.Registration getRegistration() {
      return registration_ == null ? com.spiky.server.protomodels.RegistrationLoginModels.Registration.getDefaultInstance() : registration_;
    }
    /**
     * <code>optional .Registration registration = 3;</code>
     */
    public com.spiky.server.protomodels.RegistrationLoginModels.RegistrationOrBuilder getRegistrationOrBuilder() {
      return getRegistration();
    }

    public static final int LOGIN_FIELD_NUMBER = 4;
    private com.spiky.server.protomodels.RegistrationLoginModels.Login login_;
    /**
     * <code>optional .Login login = 4;</code>
     */
    public boolean hasLogin() {
      return login_ != null;
    }
    /**
     * <code>optional .Login login = 4;</code>
     */
    public com.spiky.server.protomodels.RegistrationLoginModels.Login getLogin() {
      return login_ == null ? com.spiky.server.protomodels.RegistrationLoginModels.Login.getDefaultInstance() : login_;
    }
    /**
     * <code>optional .Login login = 4;</code>
     */
    public com.spiky.server.protomodels.RegistrationLoginModels.LoginOrBuilder getLoginOrBuilder() {
      return getLogin();
    }

    public static final int CRYPTOGRAMWRAPPER_FIELD_NUMBER = 5;
    private com.spiky.server.protomodels.MessageModels.CryptogramWrapper cryptogramWrapper_;
    /**
     * <code>optional .CryptogramWrapper cryptogramWrapper = 5;</code>
     */
    public boolean hasCryptogramWrapper() {
      return cryptogramWrapper_ != null;
    }
    /**
     * <code>optional .CryptogramWrapper cryptogramWrapper = 5;</code>
     */
    public com.spiky.server.protomodels.MessageModels.CryptogramWrapper getCryptogramWrapper() {
      return cryptogramWrapper_ == null ? com.spiky.server.protomodels.MessageModels.CryptogramWrapper.getDefaultInstance() : cryptogramWrapper_;
    }
    /**
     * <code>optional .CryptogramWrapper cryptogramWrapper = 5;</code>
     */
    public com.spiky.server.protomodels.MessageModels.CryptogramWrapperOrBuilder getCryptogramWrapperOrBuilder() {
      return getCryptogramWrapper();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (utility_ != null) {
        output.writeMessage(1, getUtility());
      }
      if (inputChecking_ != null) {
        output.writeMessage(2, getInputChecking());
      }
      if (registration_ != null) {
        output.writeMessage(3, getRegistration());
      }
      if (login_ != null) {
        output.writeMessage(4, getLogin());
      }
      if (cryptogramWrapper_ != null) {
        output.writeMessage(5, getCryptogramWrapper());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (utility_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getUtility());
      }
      if (inputChecking_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getInputChecking());
      }
      if (registration_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getRegistration());
      }
      if (login_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getLogin());
      }
      if (cryptogramWrapper_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getCryptogramWrapper());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.spiky.server.protomodels.MessageModels.Wrapper)) {
        return super.equals(obj);
      }
      com.spiky.server.protomodels.MessageModels.Wrapper other = (com.spiky.server.protomodels.MessageModels.Wrapper) obj;

      boolean result = true;
      result = result && (hasUtility() == other.hasUtility());
      if (hasUtility()) {
        result = result && getUtility()
            .equals(other.getUtility());
      }
      result = result && (hasInputChecking() == other.hasInputChecking());
      if (hasInputChecking()) {
        result = result && getInputChecking()
            .equals(other.getInputChecking());
      }
      result = result && (hasRegistration() == other.hasRegistration());
      if (hasRegistration()) {
        result = result && getRegistration()
            .equals(other.getRegistration());
      }
      result = result && (hasLogin() == other.hasLogin());
      if (hasLogin()) {
        result = result && getLogin()
            .equals(other.getLogin());
      }
      result = result && (hasCryptogramWrapper() == other.hasCryptogramWrapper());
      if (hasCryptogramWrapper()) {
        result = result && getCryptogramWrapper()
            .equals(other.getCryptogramWrapper());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasUtility()) {
        hash = (37 * hash) + UTILITY_FIELD_NUMBER;
        hash = (53 * hash) + getUtility().hashCode();
      }
      if (hasInputChecking()) {
        hash = (37 * hash) + INPUTCHECKING_FIELD_NUMBER;
        hash = (53 * hash) + getInputChecking().hashCode();
      }
      if (hasRegistration()) {
        hash = (37 * hash) + REGISTRATION_FIELD_NUMBER;
        hash = (53 * hash) + getRegistration().hashCode();
      }
      if (hasLogin()) {
        hash = (37 * hash) + LOGIN_FIELD_NUMBER;
        hash = (53 * hash) + getLogin().hashCode();
      }
      if (hasCryptogramWrapper()) {
        hash = (37 * hash) + CRYPTOGRAMWRAPPER_FIELD_NUMBER;
        hash = (53 * hash) + getCryptogramWrapper().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.spiky.server.protomodels.MessageModels.Wrapper parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.spiky.server.protomodels.MessageModels.Wrapper parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.spiky.server.protomodels.MessageModels.Wrapper parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.spiky.server.protomodels.MessageModels.Wrapper parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.spiky.server.protomodels.MessageModels.Wrapper parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.spiky.server.protomodels.MessageModels.Wrapper parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.spiky.server.protomodels.MessageModels.Wrapper parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.spiky.server.protomodels.MessageModels.Wrapper parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.spiky.server.protomodels.MessageModels.Wrapper parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.spiky.server.protomodels.MessageModels.Wrapper parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.spiky.server.protomodels.MessageModels.Wrapper prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Wrapper}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Wrapper)
        com.spiky.server.protomodels.MessageModels.WrapperOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.spiky.server.protomodels.MessageModels.internal_static_Wrapper_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.spiky.server.protomodels.MessageModels.internal_static_Wrapper_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.spiky.server.protomodels.MessageModels.Wrapper.class, com.spiky.server.protomodels.MessageModels.Wrapper.Builder.class);
      }

      // Construct using com.spiky.server.protomodels.MessageModels.Wrapper.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (utilityBuilder_ == null) {
          utility_ = null;
        } else {
          utility_ = null;
          utilityBuilder_ = null;
        }
        if (inputCheckingBuilder_ == null) {
          inputChecking_ = null;
        } else {
          inputChecking_ = null;
          inputCheckingBuilder_ = null;
        }
        if (registrationBuilder_ == null) {
          registration_ = null;
        } else {
          registration_ = null;
          registrationBuilder_ = null;
        }
        if (loginBuilder_ == null) {
          login_ = null;
        } else {
          login_ = null;
          loginBuilder_ = null;
        }
        if (cryptogramWrapperBuilder_ == null) {
          cryptogramWrapper_ = null;
        } else {
          cryptogramWrapper_ = null;
          cryptogramWrapperBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.spiky.server.protomodels.MessageModels.internal_static_Wrapper_descriptor;
      }

      public com.spiky.server.protomodels.MessageModels.Wrapper getDefaultInstanceForType() {
        return com.spiky.server.protomodels.MessageModels.Wrapper.getDefaultInstance();
      }

      public com.spiky.server.protomodels.MessageModels.Wrapper build() {
        com.spiky.server.protomodels.MessageModels.Wrapper result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.spiky.server.protomodels.MessageModels.Wrapper buildPartial() {
        com.spiky.server.protomodels.MessageModels.Wrapper result = new com.spiky.server.protomodels.MessageModels.Wrapper(this);
        if (utilityBuilder_ == null) {
          result.utility_ = utility_;
        } else {
          result.utility_ = utilityBuilder_.build();
        }
        if (inputCheckingBuilder_ == null) {
          result.inputChecking_ = inputChecking_;
        } else {
          result.inputChecking_ = inputCheckingBuilder_.build();
        }
        if (registrationBuilder_ == null) {
          result.registration_ = registration_;
        } else {
          result.registration_ = registrationBuilder_.build();
        }
        if (loginBuilder_ == null) {
          result.login_ = login_;
        } else {
          result.login_ = loginBuilder_.build();
        }
        if (cryptogramWrapperBuilder_ == null) {
          result.cryptogramWrapper_ = cryptogramWrapper_;
        } else {
          result.cryptogramWrapper_ = cryptogramWrapperBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.spiky.server.protomodels.MessageModels.Wrapper) {
          return mergeFrom((com.spiky.server.protomodels.MessageModels.Wrapper)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.spiky.server.protomodels.MessageModels.Wrapper other) {
        if (other == com.spiky.server.protomodels.MessageModels.Wrapper.getDefaultInstance()) return this;
        if (other.hasUtility()) {
          mergeUtility(other.getUtility());
        }
        if (other.hasInputChecking()) {
          mergeInputChecking(other.getInputChecking());
        }
        if (other.hasRegistration()) {
          mergeRegistration(other.getRegistration());
        }
        if (other.hasLogin()) {
          mergeLogin(other.getLogin());
        }
        if (other.hasCryptogramWrapper()) {
          mergeCryptogramWrapper(other.getCryptogramWrapper());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.spiky.server.protomodels.MessageModels.Wrapper parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.spiky.server.protomodels.MessageModels.Wrapper) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.spiky.server.protomodels.UtilityModels.Utility utility_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.spiky.server.protomodels.UtilityModels.Utility, com.spiky.server.protomodels.UtilityModels.Utility.Builder, com.spiky.server.protomodels.UtilityModels.UtilityOrBuilder> utilityBuilder_;
      /**
       * <code>optional .Utility utility = 1;</code>
       */
      public boolean hasUtility() {
        return utilityBuilder_ != null || utility_ != null;
      }
      /**
       * <code>optional .Utility utility = 1;</code>
       */
      public com.spiky.server.protomodels.UtilityModels.Utility getUtility() {
        if (utilityBuilder_ == null) {
          return utility_ == null ? com.spiky.server.protomodels.UtilityModels.Utility.getDefaultInstance() : utility_;
        } else {
          return utilityBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Utility utility = 1;</code>
       */
      public Builder setUtility(com.spiky.server.protomodels.UtilityModels.Utility value) {
        if (utilityBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          utility_ = value;
          onChanged();
        } else {
          utilityBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .Utility utility = 1;</code>
       */
      public Builder setUtility(
          com.spiky.server.protomodels.UtilityModels.Utility.Builder builderForValue) {
        if (utilityBuilder_ == null) {
          utility_ = builderForValue.build();
          onChanged();
        } else {
          utilityBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .Utility utility = 1;</code>
       */
      public Builder mergeUtility(com.spiky.server.protomodels.UtilityModels.Utility value) {
        if (utilityBuilder_ == null) {
          if (utility_ != null) {
            utility_ =
              com.spiky.server.protomodels.UtilityModels.Utility.newBuilder(utility_).mergeFrom(value).buildPartial();
          } else {
            utility_ = value;
          }
          onChanged();
        } else {
          utilityBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .Utility utility = 1;</code>
       */
      public Builder clearUtility() {
        if (utilityBuilder_ == null) {
          utility_ = null;
          onChanged();
        } else {
          utility_ = null;
          utilityBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .Utility utility = 1;</code>
       */
      public com.spiky.server.protomodels.UtilityModels.Utility.Builder getUtilityBuilder() {
        
        onChanged();
        return getUtilityFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Utility utility = 1;</code>
       */
      public com.spiky.server.protomodels.UtilityModels.UtilityOrBuilder getUtilityOrBuilder() {
        if (utilityBuilder_ != null) {
          return utilityBuilder_.getMessageOrBuilder();
        } else {
          return utility_ == null ?
              com.spiky.server.protomodels.UtilityModels.Utility.getDefaultInstance() : utility_;
        }
      }
      /**
       * <code>optional .Utility utility = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.spiky.server.protomodels.UtilityModels.Utility, com.spiky.server.protomodels.UtilityModels.Utility.Builder, com.spiky.server.protomodels.UtilityModels.UtilityOrBuilder> 
          getUtilityFieldBuilder() {
        if (utilityBuilder_ == null) {
          utilityBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.spiky.server.protomodels.UtilityModels.Utility, com.spiky.server.protomodels.UtilityModels.Utility.Builder, com.spiky.server.protomodels.UtilityModels.UtilityOrBuilder>(
                  getUtility(),
                  getParentForChildren(),
                  isClean());
          utility_ = null;
        }
        return utilityBuilder_;
      }

      private com.spiky.server.protomodels.RegistrationLoginModels.InputChecking inputChecking_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.spiky.server.protomodels.RegistrationLoginModels.InputChecking, com.spiky.server.protomodels.RegistrationLoginModels.InputChecking.Builder, com.spiky.server.protomodels.RegistrationLoginModels.InputCheckingOrBuilder> inputCheckingBuilder_;
      /**
       * <code>optional .InputChecking inputChecking = 2;</code>
       */
      public boolean hasInputChecking() {
        return inputCheckingBuilder_ != null || inputChecking_ != null;
      }
      /**
       * <code>optional .InputChecking inputChecking = 2;</code>
       */
      public com.spiky.server.protomodels.RegistrationLoginModels.InputChecking getInputChecking() {
        if (inputCheckingBuilder_ == null) {
          return inputChecking_ == null ? com.spiky.server.protomodels.RegistrationLoginModels.InputChecking.getDefaultInstance() : inputChecking_;
        } else {
          return inputCheckingBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .InputChecking inputChecking = 2;</code>
       */
      public Builder setInputChecking(com.spiky.server.protomodels.RegistrationLoginModels.InputChecking value) {
        if (inputCheckingBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          inputChecking_ = value;
          onChanged();
        } else {
          inputCheckingBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .InputChecking inputChecking = 2;</code>
       */
      public Builder setInputChecking(
          com.spiky.server.protomodels.RegistrationLoginModels.InputChecking.Builder builderForValue) {
        if (inputCheckingBuilder_ == null) {
          inputChecking_ = builderForValue.build();
          onChanged();
        } else {
          inputCheckingBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .InputChecking inputChecking = 2;</code>
       */
      public Builder mergeInputChecking(com.spiky.server.protomodels.RegistrationLoginModels.InputChecking value) {
        if (inputCheckingBuilder_ == null) {
          if (inputChecking_ != null) {
            inputChecking_ =
              com.spiky.server.protomodels.RegistrationLoginModels.InputChecking.newBuilder(inputChecking_).mergeFrom(value).buildPartial();
          } else {
            inputChecking_ = value;
          }
          onChanged();
        } else {
          inputCheckingBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .InputChecking inputChecking = 2;</code>
       */
      public Builder clearInputChecking() {
        if (inputCheckingBuilder_ == null) {
          inputChecking_ = null;
          onChanged();
        } else {
          inputChecking_ = null;
          inputCheckingBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .InputChecking inputChecking = 2;</code>
       */
      public com.spiky.server.protomodels.RegistrationLoginModels.InputChecking.Builder getInputCheckingBuilder() {
        
        onChanged();
        return getInputCheckingFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .InputChecking inputChecking = 2;</code>
       */
      public com.spiky.server.protomodels.RegistrationLoginModels.InputCheckingOrBuilder getInputCheckingOrBuilder() {
        if (inputCheckingBuilder_ != null) {
          return inputCheckingBuilder_.getMessageOrBuilder();
        } else {
          return inputChecking_ == null ?
              com.spiky.server.protomodels.RegistrationLoginModels.InputChecking.getDefaultInstance() : inputChecking_;
        }
      }
      /**
       * <code>optional .InputChecking inputChecking = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.spiky.server.protomodels.RegistrationLoginModels.InputChecking, com.spiky.server.protomodels.RegistrationLoginModels.InputChecking.Builder, com.spiky.server.protomodels.RegistrationLoginModels.InputCheckingOrBuilder> 
          getInputCheckingFieldBuilder() {
        if (inputCheckingBuilder_ == null) {
          inputCheckingBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.spiky.server.protomodels.RegistrationLoginModels.InputChecking, com.spiky.server.protomodels.RegistrationLoginModels.InputChecking.Builder, com.spiky.server.protomodels.RegistrationLoginModels.InputCheckingOrBuilder>(
                  getInputChecking(),
                  getParentForChildren(),
                  isClean());
          inputChecking_ = null;
        }
        return inputCheckingBuilder_;
      }

      private com.spiky.server.protomodels.RegistrationLoginModels.Registration registration_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.spiky.server.protomodels.RegistrationLoginModels.Registration, com.spiky.server.protomodels.RegistrationLoginModels.Registration.Builder, com.spiky.server.protomodels.RegistrationLoginModels.RegistrationOrBuilder> registrationBuilder_;
      /**
       * <code>optional .Registration registration = 3;</code>
       */
      public boolean hasRegistration() {
        return registrationBuilder_ != null || registration_ != null;
      }
      /**
       * <code>optional .Registration registration = 3;</code>
       */
      public com.spiky.server.protomodels.RegistrationLoginModels.Registration getRegistration() {
        if (registrationBuilder_ == null) {
          return registration_ == null ? com.spiky.server.protomodels.RegistrationLoginModels.Registration.getDefaultInstance() : registration_;
        } else {
          return registrationBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Registration registration = 3;</code>
       */
      public Builder setRegistration(com.spiky.server.protomodels.RegistrationLoginModels.Registration value) {
        if (registrationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          registration_ = value;
          onChanged();
        } else {
          registrationBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .Registration registration = 3;</code>
       */
      public Builder setRegistration(
          com.spiky.server.protomodels.RegistrationLoginModels.Registration.Builder builderForValue) {
        if (registrationBuilder_ == null) {
          registration_ = builderForValue.build();
          onChanged();
        } else {
          registrationBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .Registration registration = 3;</code>
       */
      public Builder mergeRegistration(com.spiky.server.protomodels.RegistrationLoginModels.Registration value) {
        if (registrationBuilder_ == null) {
          if (registration_ != null) {
            registration_ =
              com.spiky.server.protomodels.RegistrationLoginModels.Registration.newBuilder(registration_).mergeFrom(value).buildPartial();
          } else {
            registration_ = value;
          }
          onChanged();
        } else {
          registrationBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .Registration registration = 3;</code>
       */
      public Builder clearRegistration() {
        if (registrationBuilder_ == null) {
          registration_ = null;
          onChanged();
        } else {
          registration_ = null;
          registrationBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .Registration registration = 3;</code>
       */
      public com.spiky.server.protomodels.RegistrationLoginModels.Registration.Builder getRegistrationBuilder() {
        
        onChanged();
        return getRegistrationFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Registration registration = 3;</code>
       */
      public com.spiky.server.protomodels.RegistrationLoginModels.RegistrationOrBuilder getRegistrationOrBuilder() {
        if (registrationBuilder_ != null) {
          return registrationBuilder_.getMessageOrBuilder();
        } else {
          return registration_ == null ?
              com.spiky.server.protomodels.RegistrationLoginModels.Registration.getDefaultInstance() : registration_;
        }
      }
      /**
       * <code>optional .Registration registration = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.spiky.server.protomodels.RegistrationLoginModels.Registration, com.spiky.server.protomodels.RegistrationLoginModels.Registration.Builder, com.spiky.server.protomodels.RegistrationLoginModels.RegistrationOrBuilder> 
          getRegistrationFieldBuilder() {
        if (registrationBuilder_ == null) {
          registrationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.spiky.server.protomodels.RegistrationLoginModels.Registration, com.spiky.server.protomodels.RegistrationLoginModels.Registration.Builder, com.spiky.server.protomodels.RegistrationLoginModels.RegistrationOrBuilder>(
                  getRegistration(),
                  getParentForChildren(),
                  isClean());
          registration_ = null;
        }
        return registrationBuilder_;
      }

      private com.spiky.server.protomodels.RegistrationLoginModels.Login login_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.spiky.server.protomodels.RegistrationLoginModels.Login, com.spiky.server.protomodels.RegistrationLoginModels.Login.Builder, com.spiky.server.protomodels.RegistrationLoginModels.LoginOrBuilder> loginBuilder_;
      /**
       * <code>optional .Login login = 4;</code>
       */
      public boolean hasLogin() {
        return loginBuilder_ != null || login_ != null;
      }
      /**
       * <code>optional .Login login = 4;</code>
       */
      public com.spiky.server.protomodels.RegistrationLoginModels.Login getLogin() {
        if (loginBuilder_ == null) {
          return login_ == null ? com.spiky.server.protomodels.RegistrationLoginModels.Login.getDefaultInstance() : login_;
        } else {
          return loginBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Login login = 4;</code>
       */
      public Builder setLogin(com.spiky.server.protomodels.RegistrationLoginModels.Login value) {
        if (loginBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          login_ = value;
          onChanged();
        } else {
          loginBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .Login login = 4;</code>
       */
      public Builder setLogin(
          com.spiky.server.protomodels.RegistrationLoginModels.Login.Builder builderForValue) {
        if (loginBuilder_ == null) {
          login_ = builderForValue.build();
          onChanged();
        } else {
          loginBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .Login login = 4;</code>
       */
      public Builder mergeLogin(com.spiky.server.protomodels.RegistrationLoginModels.Login value) {
        if (loginBuilder_ == null) {
          if (login_ != null) {
            login_ =
              com.spiky.server.protomodels.RegistrationLoginModels.Login.newBuilder(login_).mergeFrom(value).buildPartial();
          } else {
            login_ = value;
          }
          onChanged();
        } else {
          loginBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .Login login = 4;</code>
       */
      public Builder clearLogin() {
        if (loginBuilder_ == null) {
          login_ = null;
          onChanged();
        } else {
          login_ = null;
          loginBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .Login login = 4;</code>
       */
      public com.spiky.server.protomodels.RegistrationLoginModels.Login.Builder getLoginBuilder() {
        
        onChanged();
        return getLoginFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Login login = 4;</code>
       */
      public com.spiky.server.protomodels.RegistrationLoginModels.LoginOrBuilder getLoginOrBuilder() {
        if (loginBuilder_ != null) {
          return loginBuilder_.getMessageOrBuilder();
        } else {
          return login_ == null ?
              com.spiky.server.protomodels.RegistrationLoginModels.Login.getDefaultInstance() : login_;
        }
      }
      /**
       * <code>optional .Login login = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.spiky.server.protomodels.RegistrationLoginModels.Login, com.spiky.server.protomodels.RegistrationLoginModels.Login.Builder, com.spiky.server.protomodels.RegistrationLoginModels.LoginOrBuilder> 
          getLoginFieldBuilder() {
        if (loginBuilder_ == null) {
          loginBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.spiky.server.protomodels.RegistrationLoginModels.Login, com.spiky.server.protomodels.RegistrationLoginModels.Login.Builder, com.spiky.server.protomodels.RegistrationLoginModels.LoginOrBuilder>(
                  getLogin(),
                  getParentForChildren(),
                  isClean());
          login_ = null;
        }
        return loginBuilder_;
      }

      private com.spiky.server.protomodels.MessageModels.CryptogramWrapper cryptogramWrapper_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.spiky.server.protomodels.MessageModels.CryptogramWrapper, com.spiky.server.protomodels.MessageModels.CryptogramWrapper.Builder, com.spiky.server.protomodels.MessageModels.CryptogramWrapperOrBuilder> cryptogramWrapperBuilder_;
      /**
       * <code>optional .CryptogramWrapper cryptogramWrapper = 5;</code>
       */
      public boolean hasCryptogramWrapper() {
        return cryptogramWrapperBuilder_ != null || cryptogramWrapper_ != null;
      }
      /**
       * <code>optional .CryptogramWrapper cryptogramWrapper = 5;</code>
       */
      public com.spiky.server.protomodels.MessageModels.CryptogramWrapper getCryptogramWrapper() {
        if (cryptogramWrapperBuilder_ == null) {
          return cryptogramWrapper_ == null ? com.spiky.server.protomodels.MessageModels.CryptogramWrapper.getDefaultInstance() : cryptogramWrapper_;
        } else {
          return cryptogramWrapperBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .CryptogramWrapper cryptogramWrapper = 5;</code>
       */
      public Builder setCryptogramWrapper(com.spiky.server.protomodels.MessageModels.CryptogramWrapper value) {
        if (cryptogramWrapperBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          cryptogramWrapper_ = value;
          onChanged();
        } else {
          cryptogramWrapperBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .CryptogramWrapper cryptogramWrapper = 5;</code>
       */
      public Builder setCryptogramWrapper(
          com.spiky.server.protomodels.MessageModels.CryptogramWrapper.Builder builderForValue) {
        if (cryptogramWrapperBuilder_ == null) {
          cryptogramWrapper_ = builderForValue.build();
          onChanged();
        } else {
          cryptogramWrapperBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .CryptogramWrapper cryptogramWrapper = 5;</code>
       */
      public Builder mergeCryptogramWrapper(com.spiky.server.protomodels.MessageModels.CryptogramWrapper value) {
        if (cryptogramWrapperBuilder_ == null) {
          if (cryptogramWrapper_ != null) {
            cryptogramWrapper_ =
              com.spiky.server.protomodels.MessageModels.CryptogramWrapper.newBuilder(cryptogramWrapper_).mergeFrom(value).buildPartial();
          } else {
            cryptogramWrapper_ = value;
          }
          onChanged();
        } else {
          cryptogramWrapperBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .CryptogramWrapper cryptogramWrapper = 5;</code>
       */
      public Builder clearCryptogramWrapper() {
        if (cryptogramWrapperBuilder_ == null) {
          cryptogramWrapper_ = null;
          onChanged();
        } else {
          cryptogramWrapper_ = null;
          cryptogramWrapperBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .CryptogramWrapper cryptogramWrapper = 5;</code>
       */
      public com.spiky.server.protomodels.MessageModels.CryptogramWrapper.Builder getCryptogramWrapperBuilder() {
        
        onChanged();
        return getCryptogramWrapperFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .CryptogramWrapper cryptogramWrapper = 5;</code>
       */
      public com.spiky.server.protomodels.MessageModels.CryptogramWrapperOrBuilder getCryptogramWrapperOrBuilder() {
        if (cryptogramWrapperBuilder_ != null) {
          return cryptogramWrapperBuilder_.getMessageOrBuilder();
        } else {
          return cryptogramWrapper_ == null ?
              com.spiky.server.protomodels.MessageModels.CryptogramWrapper.getDefaultInstance() : cryptogramWrapper_;
        }
      }
      /**
       * <code>optional .CryptogramWrapper cryptogramWrapper = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.spiky.server.protomodels.MessageModels.CryptogramWrapper, com.spiky.server.protomodels.MessageModels.CryptogramWrapper.Builder, com.spiky.server.protomodels.MessageModels.CryptogramWrapperOrBuilder> 
          getCryptogramWrapperFieldBuilder() {
        if (cryptogramWrapperBuilder_ == null) {
          cryptogramWrapperBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.spiky.server.protomodels.MessageModels.CryptogramWrapper, com.spiky.server.protomodels.MessageModels.CryptogramWrapper.Builder, com.spiky.server.protomodels.MessageModels.CryptogramWrapperOrBuilder>(
                  getCryptogramWrapper(),
                  getParentForChildren(),
                  isClean());
          cryptogramWrapper_ = null;
        }
        return cryptogramWrapperBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Wrapper)
    }

    // @@protoc_insertion_point(class_scope:Wrapper)
    private static final com.spiky.server.protomodels.MessageModels.Wrapper DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.spiky.server.protomodels.MessageModels.Wrapper();
    }

    public static com.spiky.server.protomodels.MessageModels.Wrapper getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Wrapper>
        PARSER = new com.google.protobuf.AbstractParser<Wrapper>() {
      public Wrapper parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Wrapper(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Wrapper> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Wrapper> getParserForType() {
      return PARSER;
    }

    public com.spiky.server.protomodels.MessageModels.Wrapper getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CryptogramWrapper_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CryptogramWrapper_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Wrapper_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Wrapper_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023MessageModels.proto\032\023UtilityModels.pro" +
      "to\032\022RegLogModels.proto\032\025DisableWarnings." +
      "proto\"\202\001\n\021CryptogramWrapper\022\024\n\014registrat" +
      "ion\030\001 \001(\014\022\r\n\005login\030\002 \001(\014\022\024\n\014initialState" +
      "\030\003 \001(\014\022\014\n\004room\030\004 \001(\014\022\020\n\010mainMenu\030\005 \001(\014\022\022" +
      "\n\ngameModels\030\006 \001(\014\"\266\001\n\007Wrapper\022\031\n\007utilit" +
      "y\030\001 \001(\0132\010.Utility\022%\n\rinputChecking\030\002 \001(\013" +
      "2\016.InputChecking\022#\n\014registration\030\003 \001(\0132\r" +
      ".Registration\022\025\n\005login\030\004 \001(\0132\006.Login\022-\n\021" +
      "cryptogramWrapper\030\005 \001(\0132\022.CryptogramWrap",
      "perB-\n\034com.spiky.server.protomodelsB\rMes" +
      "sageModelsb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.spiky.server.protomodels.UtilityModels.getDescriptor(),
          com.spiky.server.protomodels.RegistrationLoginModels.getDescriptor(),
          com.spiky.server.protomodels.DisableWarnings.getDescriptor(),
        }, assigner);
    internal_static_CryptogramWrapper_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CryptogramWrapper_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_CryptogramWrapper_descriptor,
        new java.lang.String[] { "Registration", "Login", "InitialState", "Room", "MainMenu", "GameModels", });
    internal_static_Wrapper_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Wrapper_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Wrapper_descriptor,
        new java.lang.String[] { "Utility", "InputChecking", "Registration", "Login", "CryptogramWrapper", });
    com.spiky.server.protomodels.UtilityModels.getDescriptor();
    com.spiky.server.protomodels.RegistrationLoginModels.getDescriptor();
    com.spiky.server.protomodels.DisableWarnings.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
