// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UtilityModels.proto

#ifndef PROTOBUF_UtilityModels_2eproto__INCLUDED
#define PROTOBUF_UtilityModels_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "DisableWarnings.pb.h"
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_UtilityModels_2eproto();
void protobuf_AssignDesc_UtilityModels_2eproto();
void protobuf_ShutdownFile_UtilityModels_2eproto();

class Utility;

// ===================================================================

class Utility : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Utility) */ {
 public:
  Utility();
  virtual ~Utility();

  Utility(const Utility& from);

  inline Utility& operator=(const Utility& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Utility& default_instance();

  void Swap(Utility* other);

  // implements Message ----------------------------------------------

  inline Utility* New() const { return New(NULL); }

  Utility* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Utility& from);
  void MergeFrom(const Utility& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Utility* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bool alive = 1;
  void clear_alive();
  static const int kAliveFieldNumber = 1;
  bool alive() const;
  void set_alive(bool value);

  // @@protoc_insertion_point(class_scope:Utility)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  bool alive_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_UtilityModels_2eproto();
  friend void protobuf_AssignDesc_UtilityModels_2eproto();
  friend void protobuf_ShutdownFile_UtilityModels_2eproto();

  void InitAsDefaultInstance();
  static Utility* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Utility

// optional bool alive = 1;
inline void Utility::clear_alive() {
  alive_ = false;
}
inline bool Utility::alive() const {
  // @@protoc_insertion_point(field_get:Utility.alive)
  return alive_;
}
inline void Utility::set_alive(bool value) {
  
  alive_ = value;
  // @@protoc_insertion_point(field_set:Utility.alive)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_UtilityModels_2eproto__INCLUDED
